# Generated by Django 5.0 on 2024-07-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
    ]
