# Generated by Django 5.0 on 2023-12-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('preparation_time', models.IntegerField()),
                ('preparation_time_unit', models.CharField(max_length=30)),
                ('servings', models.IntegerField()),
                ('servings_unit', models.CharField(max_length=30)),
                ('preparation_steps', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
